# frozen_string_literal: true

# Impostazioni minime incorporate nella box. CPU, RAM, reti, hostname e nested
# virtualization restano responsabilità del Vagrantfile del laboratorio.
Vagrant.configure('2') do |config|
  config.ssh.username = 'vagrant'
  config.ssh.insert_key = true
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
